// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/admin/admin.proto

package adminpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EditUserDetailsRequest struct {
	Phone                string         `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	FirstName            string         `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string         `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string         `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Role                 string         `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	UserId               string         `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CommonRequest        *CommonRequest `protobuf:"bytes,7,opt,name=common_request,json=commonRequest,proto3" json:"common_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *EditUserDetailsRequest) Reset()         { *m = EditUserDetailsRequest{} }
func (m *EditUserDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*EditUserDetailsRequest) ProtoMessage()    {}
func (*EditUserDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47a39374a10a5856, []int{0}
}

func (m *EditUserDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditUserDetailsRequest.Unmarshal(m, b)
}
func (m *EditUserDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditUserDetailsRequest.Marshal(b, m, deterministic)
}
func (m *EditUserDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditUserDetailsRequest.Merge(m, src)
}
func (m *EditUserDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_EditUserDetailsRequest.Size(m)
}
func (m *EditUserDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditUserDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditUserDetailsRequest proto.InternalMessageInfo

func (m *EditUserDetailsRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *EditUserDetailsRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *EditUserDetailsRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *EditUserDetailsRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EditUserDetailsRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *EditUserDetailsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *EditUserDetailsRequest) GetCommonRequest() *CommonRequest {
	if m != nil {
		return m.CommonRequest
	}
	return nil
}

type CommonResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47a39374a10a5856, []int{1}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CommonResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CommonResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type CommonRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonRequest) Reset()         { *m = CommonRequest{} }
func (m *CommonRequest) String() string { return proto.CompactTextString(m) }
func (*CommonRequest) ProtoMessage()    {}
func (*CommonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47a39374a10a5856, []int{2}
}

func (m *CommonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonRequest.Unmarshal(m, b)
}
func (m *CommonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonRequest.Marshal(b, m, deterministic)
}
func (m *CommonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonRequest.Merge(m, src)
}
func (m *CommonRequest) XXX_Size() int {
	return xxx_messageInfo_CommonRequest.Size(m)
}
func (m *CommonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommonRequest proto.InternalMessageInfo

func (m *CommonRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type TweetAdminRequest struct {
	Tweet                string         `protobuf:"bytes,1,opt,name=tweet,proto3" json:"tweet,omitempty"`
	UserId               string         `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CommonRequest        *CommonRequest `protobuf:"bytes,3,opt,name=common_request,json=commonRequest,proto3" json:"common_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TweetAdminRequest) Reset()         { *m = TweetAdminRequest{} }
func (m *TweetAdminRequest) String() string { return proto.CompactTextString(m) }
func (*TweetAdminRequest) ProtoMessage()    {}
func (*TweetAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47a39374a10a5856, []int{3}
}

func (m *TweetAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TweetAdminRequest.Unmarshal(m, b)
}
func (m *TweetAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TweetAdminRequest.Marshal(b, m, deterministic)
}
func (m *TweetAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TweetAdminRequest.Merge(m, src)
}
func (m *TweetAdminRequest) XXX_Size() int {
	return xxx_messageInfo_TweetAdminRequest.Size(m)
}
func (m *TweetAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TweetAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TweetAdminRequest proto.InternalMessageInfo

func (m *TweetAdminRequest) GetTweet() string {
	if m != nil {
		return m.Tweet
	}
	return ""
}

func (m *TweetAdminRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TweetAdminRequest) GetCommonRequest() *CommonRequest {
	if m != nil {
		return m.CommonRequest
	}
	return nil
}

type DeleteAdminTweetRequest struct {
	TweetId              string         `protobuf:"bytes,1,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	CommonRequest        *CommonRequest `protobuf:"bytes,2,opt,name=common_request,json=commonRequest,proto3" json:"common_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteAdminTweetRequest) Reset()         { *m = DeleteAdminTweetRequest{} }
func (m *DeleteAdminTweetRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAdminTweetRequest) ProtoMessage()    {}
func (*DeleteAdminTweetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47a39374a10a5856, []int{4}
}

func (m *DeleteAdminTweetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAdminTweetRequest.Unmarshal(m, b)
}
func (m *DeleteAdminTweetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAdminTweetRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAdminTweetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAdminTweetRequest.Merge(m, src)
}
func (m *DeleteAdminTweetRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAdminTweetRequest.Size(m)
}
func (m *DeleteAdminTweetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAdminTweetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAdminTweetRequest proto.InternalMessageInfo

func (m *DeleteAdminTweetRequest) GetTweetId() string {
	if m != nil {
		return m.TweetId
	}
	return ""
}

func (m *DeleteAdminTweetRequest) GetCommonRequest() *CommonRequest {
	if m != nil {
		return m.CommonRequest
	}
	return nil
}

type TweetListResponse struct {
	TweetList            []*Tweet `protobuf:"bytes,1,rep,name=tweet_list,json=tweetList,proto3" json:"tweet_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TweetListResponse) Reset()         { *m = TweetListResponse{} }
func (m *TweetListResponse) String() string { return proto.CompactTextString(m) }
func (*TweetListResponse) ProtoMessage()    {}
func (*TweetListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47a39374a10a5856, []int{5}
}

func (m *TweetListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TweetListResponse.Unmarshal(m, b)
}
func (m *TweetListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TweetListResponse.Marshal(b, m, deterministic)
}
func (m *TweetListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TweetListResponse.Merge(m, src)
}
func (m *TweetListResponse) XXX_Size() int {
	return xxx_messageInfo_TweetListResponse.Size(m)
}
func (m *TweetListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TweetListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TweetListResponse proto.InternalMessageInfo

func (m *TweetListResponse) GetTweetList() []*Tweet {
	if m != nil {
		return m.TweetList
	}
	return nil
}

type Tweet struct {
	Tweet                string   `protobuf:"bytes,1,opt,name=tweet,proto3" json:"tweet,omitempty"`
	TweetId              string   `protobuf:"bytes,2,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tweet) Reset()         { *m = Tweet{} }
func (m *Tweet) String() string { return proto.CompactTextString(m) }
func (*Tweet) ProtoMessage()    {}
func (*Tweet) Descriptor() ([]byte, []int) {
	return fileDescriptor_47a39374a10a5856, []int{6}
}

func (m *Tweet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tweet.Unmarshal(m, b)
}
func (m *Tweet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tweet.Marshal(b, m, deterministic)
}
func (m *Tweet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tweet.Merge(m, src)
}
func (m *Tweet) XXX_Size() int {
	return xxx_messageInfo_Tweet.Size(m)
}
func (m *Tweet) XXX_DiscardUnknown() {
	xxx_messageInfo_Tweet.DiscardUnknown(m)
}

var xxx_messageInfo_Tweet proto.InternalMessageInfo

func (m *Tweet) GetTweet() string {
	if m != nil {
		return m.Tweet
	}
	return ""
}

func (m *Tweet) GetTweetId() string {
	if m != nil {
		return m.TweetId
	}
	return ""
}

type AdminTweetListRequest struct {
	UserId               string         `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CommonRequest        *CommonRequest `protobuf:"bytes,2,opt,name=common_request,json=commonRequest,proto3" json:"common_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AdminTweetListRequest) Reset()         { *m = AdminTweetListRequest{} }
func (m *AdminTweetListRequest) String() string { return proto.CompactTextString(m) }
func (*AdminTweetListRequest) ProtoMessage()    {}
func (*AdminTweetListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47a39374a10a5856, []int{7}
}

func (m *AdminTweetListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminTweetListRequest.Unmarshal(m, b)
}
func (m *AdminTweetListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminTweetListRequest.Marshal(b, m, deterministic)
}
func (m *AdminTweetListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminTweetListRequest.Merge(m, src)
}
func (m *AdminTweetListRequest) XXX_Size() int {
	return xxx_messageInfo_AdminTweetListRequest.Size(m)
}
func (m *AdminTweetListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminTweetListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminTweetListRequest proto.InternalMessageInfo

func (m *AdminTweetListRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AdminTweetListRequest) GetCommonRequest() *CommonRequest {
	if m != nil {
		return m.CommonRequest
	}
	return nil
}

type AdminTweetUpdateRequest struct {
	Tweet                *Tweet         `protobuf:"bytes,1,opt,name=tweet,proto3" json:"tweet,omitempty"`
	UserId               string         `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CommonRequest        *CommonRequest `protobuf:"bytes,3,opt,name=common_request,json=commonRequest,proto3" json:"common_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AdminTweetUpdateRequest) Reset()         { *m = AdminTweetUpdateRequest{} }
func (m *AdminTweetUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*AdminTweetUpdateRequest) ProtoMessage()    {}
func (*AdminTweetUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47a39374a10a5856, []int{8}
}

func (m *AdminTweetUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminTweetUpdateRequest.Unmarshal(m, b)
}
func (m *AdminTweetUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminTweetUpdateRequest.Marshal(b, m, deterministic)
}
func (m *AdminTweetUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminTweetUpdateRequest.Merge(m, src)
}
func (m *AdminTweetUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_AdminTweetUpdateRequest.Size(m)
}
func (m *AdminTweetUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminTweetUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminTweetUpdateRequest proto.InternalMessageInfo

func (m *AdminTweetUpdateRequest) GetTweet() *Tweet {
	if m != nil {
		return m.Tweet
	}
	return nil
}

func (m *AdminTweetUpdateRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AdminTweetUpdateRequest) GetCommonRequest() *CommonRequest {
	if m != nil {
		return m.CommonRequest
	}
	return nil
}

func init() {
	proto.RegisterType((*EditUserDetailsRequest)(nil), "adminpb.EditUserDetailsRequest")
	proto.RegisterType((*CommonResponse)(nil), "adminpb.CommonResponse")
	proto.RegisterType((*CommonRequest)(nil), "adminpb.CommonRequest")
	proto.RegisterType((*TweetAdminRequest)(nil), "adminpb.TweetAdminRequest")
	proto.RegisterType((*DeleteAdminTweetRequest)(nil), "adminpb.DeleteAdminTweetRequest")
	proto.RegisterType((*TweetListResponse)(nil), "adminpb.TweetListResponse")
	proto.RegisterType((*Tweet)(nil), "adminpb.Tweet")
	proto.RegisterType((*AdminTweetListRequest)(nil), "adminpb.AdminTweetListRequest")
	proto.RegisterType((*AdminTweetUpdateRequest)(nil), "adminpb.AdminTweetUpdateRequest")
}

func init() {
	proto.RegisterFile("protos/admin/admin.proto", fileDescriptor_47a39374a10a5856)
}

var fileDescriptor_47a39374a10a5856 = []byte{
	// 618 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xe5, 0xb4, 0x69, 0x9a, 0x69, 0x9b, 0xd2, 0x55, 0x48, 0xdc, 0xb4, 0xd0, 0xd6, 0xe2,
	0x50, 0x55, 0x6a, 0x2d, 0xc2, 0x05, 0x21, 0x71, 0x80, 0x96, 0x03, 0x12, 0xe2, 0x10, 0xda, 0x73,
	0xb4, 0xb5, 0xa7, 0x61, 0xc1, 0xf6, 0x1a, 0xef, 0xa6, 0x9c, 0xe1, 0x15, 0x38, 0xf0, 0x08, 0x3c,
	0x10, 0xaf, 0xc0, 0x91, 0x87, 0x40, 0x3b, 0x6b, 0x27, 0x4e, 0x1a, 0xab, 0xca, 0x81, 0x4b, 0xe5,
	0x99, 0xad, 0xf7, 0xfb, 0xff, 0x7f, 0xd6, 0x1b, 0x70, 0xd3, 0x4c, 0x6a, 0xa9, 0x7c, 0x1e, 0xc6,
	0x22, 0xb1, 0x7f, 0xcf, 0xa8, 0xc5, 0x1a, 0x54, 0xa4, 0xd7, 0xbd, 0xfd, 0x91, 0x94, 0xa3, 0x08,
	0x7d, 0x9e, 0x0a, 0x9f, 0x27, 0x89, 0xd4, 0x5c, 0x0b, 0x99, 0x28, 0xfb, 0x6f, 0xde, 0x5f, 0x07,
	0x3a, 0x6f, 0x42, 0xa1, 0xaf, 0x14, 0x66, 0x17, 0xa8, 0xb9, 0x88, 0xd4, 0x00, 0xbf, 0x8c, 0x51,
	0x69, 0xd6, 0x86, 0x7a, 0xfa, 0x51, 0x26, 0xe8, 0x3a, 0x87, 0xce, 0x71, 0x73, 0x60, 0x0b, 0xf6,
	0x08, 0xe0, 0x46, 0x64, 0x4a, 0x0f, 0x13, 0x1e, 0xa3, 0x5b, 0xa3, 0xa5, 0x26, 0x75, 0xde, 0xf3,
	0x18, 0xd9, 0x1e, 0x34, 0x23, 0x5e, 0xac, 0xae, 0xd0, 0xea, 0xba, 0x69, 0xd0, 0x62, 0x1b, 0xea,
	0x18, 0x73, 0x11, 0xb9, 0xab, 0x76, 0x47, 0x2a, 0x18, 0x83, 0xd5, 0x4c, 0x46, 0xe8, 0xd6, 0xa9,
	0x49, 0xcf, 0xac, 0x0b, 0x8d, 0xb1, 0xc2, 0x6c, 0x28, 0x42, 0x77, 0x8d, 0xda, 0x6b, 0xa6, 0x7c,
	0x1b, 0xb2, 0x97, 0xd0, 0x0a, 0x64, 0x1c, 0xcb, 0x64, 0x98, 0x59, 0x99, 0x6e, 0xe3, 0xd0, 0x39,
	0xde, 0xe8, 0x77, 0xce, 0x72, 0xbf, 0x67, 0xe7, 0xb4, 0x9c, 0x9b, 0x18, 0x6c, 0x05, 0xe5, 0xd2,
	0x1b, 0x40, 0xab, 0x58, 0x57, 0xa9, 0x4c, 0x14, 0x32, 0x17, 0x1a, 0x31, 0x2a, 0xc5, 0x47, 0x85,
	0xcf, 0xa2, 0x34, 0xba, 0x02, 0x19, 0x5a, 0x8f, 0xf5, 0x01, 0x3d, 0x9b, 0x5e, 0xc8, 0x35, 0xcf,
	0x9d, 0xd1, 0xb3, 0xd7, 0x87, 0xad, 0x19, 0x26, 0x3b, 0x82, 0x4d, 0x1e, 0x04, 0xa8, 0xd4, 0x50,
	0xcb, 0xcf, 0x98, 0xe4, 0xfb, 0x6e, 0xd8, 0xde, 0xa5, 0x69, 0x79, 0xdf, 0x1c, 0xd8, 0xb9, 0xfc,
	0x8a, 0xa8, 0x5f, 0x19, 0xd5, 0xa5, 0xc4, 0xb5, 0x69, 0x16, 0x89, 0x53, 0x51, 0xce, 0xa2, 0x76,
	0x4f, 0x16, 0x2b, 0xcb, 0x64, 0xa1, 0xa0, 0x7b, 0x81, 0x11, 0x6a, 0x24, 0x0d, 0xa4, 0xa6, 0x10,
	0xb2, 0x0b, 0xeb, 0xc4, 0x36, 0xcc, 0x3c, 0x15, 0xaa, 0x17, 0x42, 0x6b, 0xcb, 0x40, 0x5f, 0xe7,
	0xbe, 0xdf, 0x09, 0xa5, 0x27, 0x33, 0x38, 0x05, 0xb0, 0xb8, 0x48, 0x28, 0x63, 0x7e, 0xe5, 0x78,
	0xa3, 0xdf, 0x9a, 0xec, 0x67, 0x95, 0x35, 0x75, 0xf1, 0x9a, 0xf7, 0x1c, 0xea, 0xd4, 0xab, 0xc8,
	0xab, 0x2c, 0xbe, 0x36, 0x23, 0xde, 0x93, 0xf0, 0x70, 0x6a, 0xd6, 0x4a, 0xb0, 0x86, 0x4b, 0x19,
	0x3b, 0xf7, 0x64, 0xbc, 0x94, 0xdd, 0x9f, 0x0e, 0x74, 0xa7, 0xc4, 0xab, 0x34, 0xe4, 0x1a, 0x0b,
	0xe6, 0x93, 0xb2, 0xfa, 0xbb, 0x86, 0xff, 0xef, 0xf4, 0xfb, 0xbf, 0x56, 0x61, 0x93, 0x94, 0x7d,
	0xc0, 0xec, 0x56, 0x04, 0xc8, 0x22, 0xd8, 0x9e, 0xbb, 0x08, 0xd8, 0xc1, 0x64, 0xab, 0xc5, 0x57,
	0x44, 0xaf, 0x7b, 0x87, 0x65, 0x27, 0xea, 0x1d, 0x7c, 0xff, 0xfd, 0xe7, 0x47, 0x6d, 0xd7, 0x6b,
	0xfb, 0xb7, 0x4f, 0x7d, 0x0c, 0x85, 0xf6, 0x8d, 0xea, 0xd0, 0xbe, 0xfd, 0xc2, 0x39, 0x61, 0x01,
	0x3c, 0x20, 0xfa, 0x79, 0x86, 0x5c, 0xa3, 0x1d, 0x67, 0x6f, 0x36, 0x81, 0xf2, 0xa7, 0x51, 0x4d,
	0xea, 0x11, 0xa9, 0xed, 0x6d, 0x1b, 0x92, 0xbd, 0x06, 0x29, 0x38, 0x03, 0xb9, 0xc9, 0x21, 0xf6,
	0x98, 0x5b, 0xc8, 0xe1, 0x64, 0xa3, 0x8a, 0xc3, 0x5f, 0x8d, 0xea, 0x12, 0x6a, 0xe7, 0x64, 0x1e,
	0xc5, 0xd2, 0x9c, 0x63, 0xe7, 0x3b, 0xcf, 0xa9, 0x98, 0x7f, 0x35, 0xe7, 0x88, 0x38, 0x7b, 0x5e,
	0x67, 0xca, 0x19, 0xd3, 0x9b, 0xa7, 0x13, 0x67, 0x9f, 0xa0, 0x45, 0xdb, 0x9a, 0x33, 0x6c, 0x79,
	0x8f, 0x17, 0xf0, 0x4a, 0x27, 0xbc, 0x37, 0x17, 0x6e, 0xf9, 0xfb, 0xf3, 0xf6, 0x09, 0xd8, 0x61,
	0xed, 0x29, 0xd0, 0x7c, 0x89, 0xd6, 0xdd, 0xf5, 0x1a, 0xfd, 0x52, 0x3c, 0xfb, 0x17, 0x00, 0x00,
	0xff, 0xff, 0x6f, 0x3a, 0xb7, 0xe7, 0x6c, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminServiceClient interface {
	EditUserDetails(ctx context.Context, in *EditUserDetailsRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	// admin create tweet
	AdminCreateTweet(ctx context.Context, in *TweetAdminRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	// admin delete tweet
	AdminDeleteTweet(ctx context.Context, in *DeleteAdminTweetRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	// admin update tweet
	AdminUpdateTweet(ctx context.Context, in *AdminTweetUpdateRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	// admin list tweet
	AdminListTweet(ctx context.Context, in *AdminTweetListRequest, opts ...grpc.CallOption) (*TweetListResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) EditUserDetails(ctx context.Context, in *EditUserDetailsRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/adminpb.AdminService/EditUserDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AdminCreateTweet(ctx context.Context, in *TweetAdminRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/adminpb.AdminService/AdminCreateTweet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AdminDeleteTweet(ctx context.Context, in *DeleteAdminTweetRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/adminpb.AdminService/AdminDeleteTweet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AdminUpdateTweet(ctx context.Context, in *AdminTweetUpdateRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/adminpb.AdminService/AdminUpdateTweet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AdminListTweet(ctx context.Context, in *AdminTweetListRequest, opts ...grpc.CallOption) (*TweetListResponse, error) {
	out := new(TweetListResponse)
	err := c.cc.Invoke(ctx, "/adminpb.AdminService/AdminListTweet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
type AdminServiceServer interface {
	EditUserDetails(context.Context, *EditUserDetailsRequest) (*CommonResponse, error)
	// admin create tweet
	AdminCreateTweet(context.Context, *TweetAdminRequest) (*CommonResponse, error)
	// admin delete tweet
	AdminDeleteTweet(context.Context, *DeleteAdminTweetRequest) (*CommonResponse, error)
	// admin update tweet
	AdminUpdateTweet(context.Context, *AdminTweetUpdateRequest) (*CommonResponse, error)
	// admin list tweet
	AdminListTweet(context.Context, *AdminTweetListRequest) (*TweetListResponse, error)
}

// UnimplementedAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (*UnimplementedAdminServiceServer) EditUserDetails(ctx context.Context, req *EditUserDetailsRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditUserDetails not implemented")
}
func (*UnimplementedAdminServiceServer) AdminCreateTweet(ctx context.Context, req *TweetAdminRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminCreateTweet not implemented")
}
func (*UnimplementedAdminServiceServer) AdminDeleteTweet(ctx context.Context, req *DeleteAdminTweetRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminDeleteTweet not implemented")
}
func (*UnimplementedAdminServiceServer) AdminUpdateTweet(ctx context.Context, req *AdminTweetUpdateRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUpdateTweet not implemented")
}
func (*UnimplementedAdminServiceServer) AdminListTweet(ctx context.Context, req *AdminTweetListRequest) (*TweetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminListTweet not implemented")
}

func RegisterAdminServiceServer(s *grpc.Server, srv AdminServiceServer) {
	s.RegisterService(&_AdminService_serviceDesc, srv)
}

func _AdminService_EditUserDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditUserDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).EditUserDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminpb.AdminService/EditUserDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).EditUserDetails(ctx, req.(*EditUserDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AdminCreateTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TweetAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AdminCreateTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminpb.AdminService/AdminCreateTweet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AdminCreateTweet(ctx, req.(*TweetAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AdminDeleteTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdminTweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AdminDeleteTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminpb.AdminService/AdminDeleteTweet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AdminDeleteTweet(ctx, req.(*DeleteAdminTweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AdminUpdateTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminTweetUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AdminUpdateTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminpb.AdminService/AdminUpdateTweet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AdminUpdateTweet(ctx, req.(*AdminTweetUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AdminListTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminTweetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AdminListTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminpb.AdminService/AdminListTweet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AdminListTweet(ctx, req.(*AdminTweetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "adminpb.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EditUserDetails",
			Handler:    _AdminService_EditUserDetails_Handler,
		},
		{
			MethodName: "AdminCreateTweet",
			Handler:    _AdminService_AdminCreateTweet_Handler,
		},
		{
			MethodName: "AdminDeleteTweet",
			Handler:    _AdminService_AdminDeleteTweet_Handler,
		},
		{
			MethodName: "AdminUpdateTweet",
			Handler:    _AdminService_AdminUpdateTweet_Handler,
		},
		{
			MethodName: "AdminListTweet",
			Handler:    _AdminService_AdminListTweet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/admin/admin.proto",
}
