// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/onboarding/register/register.proto

package regsiterpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterUserRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string   `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c37ae957637d7488, []int{0}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterUserRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type RegisterUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c37ae957637d7488, []int{1}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterUserResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterUserResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterUserRequest)(nil), "regsiterpb.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "regsiterpb.RegisterUserResponse")
}

func init() {
	proto.RegisterFile("protos/onboarding/register/register.proto", fileDescriptor_c37ae957637d7488)
}

var fileDescriptor_c37ae957637d7488 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x95, 0xd2, 0x94, 0xf6, 0x40, 0x42, 0x98, 0x0a, 0x45, 0xa5, 0x88, 0x92, 0x09, 0x18,
	0x1a, 0x01, 0x1b, 0x0f, 0xc1, 0x10, 0x60, 0xae, 0xdc, 0xf4, 0x30, 0x16, 0x89, 0x2f, 0xf8, 0xdc,
	0xb2, 0xb3, 0x31, 0xf3, 0x1c, 0x3c, 0x0d, 0xaf, 0xc0, 0x83, 0xa0, 0xda, 0x0d, 0x50, 0x09, 0xb6,
	0xfb, 0xbf, 0xff, 0x7c, 0xfe, 0x75, 0x07, 0xa7, 0xb5, 0x25, 0x47, 0x9c, 0x91, 0x99, 0x92, 0xb4,
	0x33, 0x6d, 0x54, 0x66, 0x51, 0x69, 0x76, 0x68, 0xbf, 0x8b, 0xb1, 0xef, 0x11, 0x60, 0x51, 0xb1,
	0x76, 0x68, 0xeb, 0xe9, 0x60, 0xa8, 0x88, 0x54, 0x89, 0x99, 0xac, 0x75, 0x26, 0x8d, 0x21, 0x27,
	0x9d, 0x26, 0xc3, 0xa1, 0x33, 0x7d, 0x8f, 0x60, 0x2f, 0x5f, 0x3d, 0xbe, 0x63, 0xb4, 0x39, 0x3e,
	0xcd, 0x91, 0x9d, 0xe8, 0x43, 0x5c, 0x3f, 0x90, 0xc1, 0x24, 0x1a, 0x45, 0x27, 0xbd, 0x3c, 0x08,
	0x71, 0x08, 0x70, 0xaf, 0x2d, 0xbb, 0x89, 0x91, 0x15, 0x26, 0x2d, 0x6f, 0xf5, 0x3c, 0xb9, 0x96,
	0x15, 0x8a, 0x03, 0xe8, 0x95, 0xb2, 0x71, 0x37, 0xbc, 0xdb, 0x5d, 0x02, 0x6f, 0xf6, 0x21, 0xc6,
	0x4a, 0xea, 0x32, 0x69, 0x87, 0x89, 0x5e, 0x88, 0x01, 0x74, 0x6b, 0xc9, 0xfc, 0x4c, 0x76, 0x96,
	0xc4, 0xe1, 0x45, 0xa3, 0x85, 0x80, 0xb6, 0xa5, 0x12, 0x93, 0x8e, 0xe7, 0xbe, 0x4e, 0x15, 0xf4,
	0xd7, 0xe3, 0x72, 0x4d, 0x86, 0x51, 0x24, 0xb0, 0x59, 0x21, 0xb3, 0x54, 0x4d, 0xe2, 0x46, 0x2e,
	0xa7, 0x14, 0x34, 0x0b, 0x69, 0xe3, 0xdc, 0xd7, 0xe2, 0x18, 0xb6, 0x65, 0x51, 0x20, 0xf3, 0xc4,
	0xd1, 0x23, 0x9a, 0x55, 0xd6, 0xad, 0xc0, 0x6e, 0x97, 0xe8, 0xe2, 0x35, 0x82, 0x9d, 0xe6, 0xa7,
	0x1b, 0xb4, 0x0b, 0x5d, 0xa0, 0x58, 0xac, 0xef, 0xaa, 0xc1, 0x47, 0xe3, 0x9f, 0x75, 0x8f, 0xff,
	0x58, 0xe6, 0x60, 0xf4, 0x7f, 0x43, 0x88, 0x9f, 0x0e, 0x5f, 0x3e, 0x3e, 0xdf, 0x5a, 0xfb, 0xe9,
	0x6e, 0xb6, 0x38, 0xcf, 0xe6, 0xfc, 0xeb, 0xa2, 0x57, 0xd1, 0xd9, 0xb4, 0xe3, 0x6f, 0x75, 0xf9,
	0x15, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xef, 0xca, 0xb9, 0x02, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RegisterServiceClient is the client API for RegisterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegisterServiceClient interface {
	RegisterUserService(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
}

type registerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegisterServiceClient(cc grpc.ClientConnInterface) RegisterServiceClient {
	return &registerServiceClient{cc}
}

func (c *registerServiceClient) RegisterUserService(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, "/regsiterpb.RegisterService/RegisterUserService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterServiceServer is the server API for RegisterService service.
type RegisterServiceServer interface {
	RegisterUserService(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
}

// UnimplementedRegisterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRegisterServiceServer struct {
}

func (*UnimplementedRegisterServiceServer) RegisterUserService(ctx context.Context, req *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUserService not implemented")
}

func RegisterRegisterServiceServer(s *grpc.Server, srv RegisterServiceServer) {
	s.RegisterService(&_RegisterService_serviceDesc, srv)
}

func _RegisterService_RegisterUserService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServiceServer).RegisterUserService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/regsiterpb.RegisterService/RegisterUserService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServiceServer).RegisterUserService(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegisterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "regsiterpb.RegisterService",
	HandlerType: (*RegisterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUserService",
			Handler:    _RegisterService_RegisterUserService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/onboarding/register/register.proto",
}
